name: Build and push socket-activate-echo container image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_push_container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run docker/setup-qemu-action
        uses: docker/setup-qemu-action@v1
      - name: Run docker/setup-buildx-action
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: List available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run docker/login-action
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run docker/metadata-action
        id: metadata_action_id
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/eriksjolund/socket-activate-echo
          flavor: |
            latest=auto
          tags: |
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=socket-activate-echo
            org.opencontainers.image.description=socket activation echo server demo
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/arm/v7
          tags: ${{ steps.metadata_action_id.outputs.tags }}
          labels: ${{ steps.metadata_action_id.outputs.labels }}
